### ISSUE TITLE
ImportError: No module named exceptions

### ISSUE THREAD

**Issue by TerrificMao** [sportarchive/CloudProcessingEngine#8]
-rwxrwxr-x 1 ubuntu ubuntu 1882 Jul 16 09:53 decider.py*
-rwxrwxr-x 1 ubuntu ubuntu 1301 Jul 16 09:23 test-worker.py*
ubuntu@ip-172-31-26-224:~/transcode20150715/CloudProcessingEngine/CloudProcessingEngine/decider/bin$ ./decider.py
Traceback (most recent call last):
  File "./decider.py", line 25, in <module>
    from pydecider.register import register
  File "/usr/local/lib/python2.7/dist-packages/pydecider/**init**.py", line 7, in <module>
    from . import activity
  File "/usr/local/lib/python2.7/dist-packages/pydecider/activity.py", line 12, in <module>
    import yaql.exceptions
ImportError: No module named exceptions

**Comment by koxon** [comment]
You are missing dependencies. 

Do `./setup.py install`
or
Use `pip install -r requirements.txt` 

Once your Pythons dependencies are met, it will work.

**Comment by TerrificMao** [comment]
Cool, thanks so much for your support!

jsonschema.exceptions.ValidationError: {'input': {'type': 'object'}, 'required': ['input'], 'type': 'object', 'properties': None} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['input_spec']:
    {'oneOf': [{'type': 'null'}, {'$ref': '#/definitions/input_spec'}]}

On instance['input_spec']:
    {'input': {'type': 'object'},
     'properties': None,
     'required': ['input'],
     'type': 'object'}

**Comment by koxon** [comment]
Which plan are you using? Make sure your yaml is correct. Use a yaml
validator to ensure it's valid.
