### ISSUE TITLE
jsonschema.exceptions.ValidationError

### ISSUE THREAD

**Issue by TerrificMao** [sportarchive/CloudProcessingEngine#9]
jsonschema.exceptions.ValidationError: {'input': {'type': 'object'}, 'required': ['input'], 'type': 'object', 'properties': None} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['input_spec']:
{'oneOf': [{'type': 'null'}, {'$ref': '#/definitions/input_spec'}]}

On instance['input_spec']:
{'input': {'type': 'object'},
'properties': None,
'required': ['input'],
'type': 'object'}

**Comment by koxon** [comment]
Which plan are you using? Make sure your yaml is correct. Use a yaml
validator to ensure it's valid.

**Comment by sunxinyu6122** [comment]
We use the /CloudProcessingEngine/decider/docs/examples/ct_plan.yml . How can I use the yaml validator?

**Comment by koxon** [comment]
yaml validator online. Search for one.

When do you get this error? When you submit a job or at startup ?

On Sun, Jul 19, 2015 at 10:18 PM, sunxinyu6122 notifications@github.com
wrote:

> We use the /CloudProcessingEngine/decider/docs/examples/ct_plan.yml . How
> can I use the yaml validator?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122730939
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by sportarc** [comment]
I am looking into the issue. I was able to reproduce.

Thanks

On Sun, Jul 19, 2015 at 10:47 PM, Nicolas Menciere <notifications@github.com

> wrote:
> 
> yaml validator online. Search for one.
> 
> When do you get this error? When you submit a job or at startup ?
> 
> On Sun, Jul 19, 2015 at 10:18 PM, sunxinyu6122 notifications@github.com
> wrote:
> 
> > We use the /CloudProcessingEngine/decider/docs/examples/ct_plan.yml . How
> > can I use the yaml validator?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122730939
> > 
> > .
> 
> ## 
> 
> Nicolas Menciere
> Co-Founder and CTO
> Sport Archive Inc.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122736369
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by sportarc** [comment]
use the ct_plan_simple.yaml for now. Like mentioned in the documentation

On Sun, Jul 19, 2015 at 11:11 PM, Nicolas Menciere <
nmenciere@sportarchive.tv> wrote:

> I am looking into the issue. I was able to reproduce.
> 
> Thanks
> 
> On Sun, Jul 19, 2015 at 10:47 PM, Nicolas Menciere <
> notifications@github.com> wrote:
> 
> > yaml validator online. Search for one.
> > 
> > When do you get this error? When you submit a job or at startup ?
> > 
> > On Sun, Jul 19, 2015 at 10:18 PM, sunxinyu6122 notifications@github.com
> > wrote:
> > 
> > > We use the /CloudProcessingEngine/decider/docs/examples/ct_plan.yml .
> > > How
> > > can I use the yaml validator?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122730939
> > > 
> > > .
> > 
> > ## 
> > 
> > Nicolas Menciere
> > Co-Founder and CTO
> > Sport Archive Inc.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122736369
> > .
> 
> ## 
> 
> Nicolas Menciere
> Co-Founder and CTO
> Sport Archive Inc.

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by sunxinyu6122** [comment]
[root@ip-172-31-10-126 decider]# ./bin/decider.py -d MyDomain -t basic_transcode --plan docs/examples/ct_plan_simple.yml &
[1] 32558
[root@ip-172-31-10-126 decider]# /usr/lib64/python2.7/dist-packages/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
  _warn("Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.", PowmInsecureWarning)
Traceback (most recent call last):
  File "./bin/decider.py", line 64, in <module>
    main()
  File "./bin/decider.py", line 53, in main
    workflows=((p.name, p.version),))
  File "/usr/local/lib/python2.7/site-packages/pydecider/register.py", line 21, in register
    registerables.append(swf.Domain(name=domain))
  File "/usr/local/lib/python2.7/site-packages/boto/swf/layer2.py", line 39, in __init__
    region=self.region)
  File "/usr/local/lib/python2.7/site-packages/boto/swf/layer1.py", line 85, in **init**
    debug, session_token, profile_name=profile_name)
  File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line 569, in **init**
    host, config, self.provider, self._required_auth_capability())
  File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 987, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials

**Comment by koxon** [comment]
You guys have to read errors before dumping it here:

 /usr/lib64/python2.7/dist-packages/Crypto/Util/number.py:57:
PowmInsecureWarning: Not using mpz_powm_sec. You should rebuild using
libgmp >= 5 to avoid timing attack vulnerability.
_warn("Not using mpz_powm_sec. You should rebuild using libgmp >= 5 to
avoid timing attack vulnerability.", PowmInsecureWarning)_

On Sun, Jul 19, 2015 at 11:20 PM, sunxinyu6122 notifications@github.com
wrote:

> [root@ip-172-31-10-126 decider]# ./bin/decider.py -d MyDomain -t
> basic_transcode --plan docs/examples/ct_plan_simple.yml &
> [1] 32558
> [root@ip-172-31-10-126 decider]#
> /usr/lib64/python2.7/dist-packages/Crypto/Util/number.py:57:
> PowmInsecureWarning: Not using mpz_powm_sec. You should rebuild using
> libgmp >= 5 to avoid timing attack vulnerability.
> 
> _warn("Not using mpz_powm_sec. You should rebuild using libgmp >= 5 to
> avoid timing attack vulnerability.", PowmInsecureWarning) Traceback (most
> recent call last): File "./bin/decider.py", line 64, in main() File
> "./bin/decider.py", line 53, in main workflows=((p.name http://p.name,
> p.version),)) File
> "/usr/local/lib/python2.7/site-packages/pydecider/register.py", line 21, in
> register registerables.append(swf.Domain(name=domain)) File
> "/usr/local/lib/python2.7/site-packages/boto/swf/layer2.py", line 39, in
> __init__
> region=self.region)
> File "/usr/local/lib/python2.7/site-packages/boto/swf/layer1.py", line 85,
> in _init_
> debug, session_token, profile_name=profile_name)
> File "/usr/local/lib/python2.7/site-packages/boto/connection.py", line
> 569, in _init_
> host, config, self.provider, self._required_auth_capability())
> File "/usr/local/lib/python2.7/site-packages/boto/auth.py", line 987, in
> get_auth_handler
> 'Check your credentials' % (len(names), str(names)))
> boto.exception.NoAuthHandlerFound: No handler was ready to authenticate. 1
> handlers were checked. ['HmacAuthV4Handler'] Check your credentials
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sportarchive/CloudProcessingEngine/issues/9#issuecomment-122746003
> .

## 

Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by koxon** [comment]
I fixed the ct_plan. Next time submit issues in the proper GitHub project. 
This is an issue with the Decider, its repo is here: https://github.com/sportarchive/CloudProcessingEngine-Decider

I just tested both plans and it works.

I raised an issue to the maintainer of the Decider as it is not resilient enough today.
It crashes upon input validation error which shouldn't happen.

But if you JSON input payload is good and the plan matches it, it should work fine.

Closing the issue.

**Comment by koxon** [comment]
I updated the documentation to add more details about how your client application must use the stack.
See those pages:
http://sportarchive.github.io/CloudProcessingEngine/comp/inputpoller.html
http://sportarchive.github.io/CloudProcessingEngine/start/use-the-stack.html

Let me know how it goes.
